version: 2.1

workflows:
    version: 2 
 jobs:
      - build:
          filters:
            branches:
              only: 
                - main
jobs:
   build:
      docker:
        - image: cimg/node:12.10

      executor: node/default

      steps:
        - node/install
        - chekout
        - run:
            name: install Dependencies
            command: npm install
   
        - run:
            name: run build
            command: npm run build    

        - run:
            name: deploy at netlify
            command: npm run deploy


 