# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows

jobs:
    build_deploy:
      docker:
        - image: cimg/node:16.10
      steps:
        - chekout

        #Download and cash dependencies
        

        - run:
            name: install Dependencies
            command: npm install


        

        - run:
            name: run test
            command: npm run test
                
        - run:
            name: run build
            command: npm run build    

        - run:
            name: deploy at netlify
            command: npm run deploy



workflows:
    build_deploy:
      jobs:
        -deploy    
        